---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-slz-ocp
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 95fccffc-ae3b-42df-b6d9-80be5914d852
    include_git_submodules: true
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-cos-instance-and-vpc.sh"
        post_validation: "tests/scripts/post-validation-destroy-cos-instance-and-vpc.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
      - name: quickstart
        mark_ready: true
        install_type: fullstack
