---
apiVersion: v1
offerings:
  - name: terraform-ibm-base-ocp-vpc
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 8531b562-91d5-4974-a195-5dff72ef2a5d
    examples:
      - name: basic
        mark_ready: true
      - name: advanced
        mark_ready: true
      - name: fscloud
        mark_ready: true
      - name: multiple_mzr_clusters
        mark_ready: true
      - name: add_rules_to_sg
        mark_ready: true
