---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-vpc
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 1f81ede7-d69d-4a07-b8d6-071b38720d6a
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
