---
apiVersion: v1
offerings:
  - name: deploy-arch-ibm-ocp-vpc
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: 1728a4fd-f561-4cf9-82ef-2b1eeb5da1a8
    variations:
      - name: fully-configurable
        mark_ready: true
        install_type: fullstack
        pre_validation: "tests/scripts/pre-validation-deploy-cos-instance-and-vpc.sh"
        post_validation: "tests/scripts/post-validation-destroy-cos-instance-and-vpc.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
      - name: quickstart
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
          scope_resource_group_var_name: existing_resource_group_name
