kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Values.metadata.name }}"
  namespace: "{{ .Values.metadata.namespace }}"
spec:
  podSelector:
    matchLabels:
      app: "{{ .Values.metadata.name }}"
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 3000
        - protocol: TCP
          port: 4443
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app: konnectivity-agent
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app: vpn
